working_dir: &working_dir ~/app
version: 2.1
jobs:
  React:
    ##################################################################
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build .
  
  React1:
    
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build .
  React2:
    
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build .
  React3:
    
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build .
  React4:
    
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build .


  
workflows:
  version: 2
  build_test_feature:
    jobs:
      - React
      - React1
      - React2
      - React3
      - React4
          
